name: Pull Request Closed

on:
  pull_request:
    types: [closed]

env:
  # azure
  resourceGroup: jldeen2022k8s
  clusterName: jldeen2022k8s
  nameSpace: bikeapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create valid deployment name
        id: generate-deployment-name
        run: |
          deployName=${GITHUB_HEAD_REF::63}        
          deployName=$(echo ${deployName//[!0-9a-zA-Z]/-} | tr '[:upper:]' '[:lower:]' | sed -e 's/^-/z/' -e 's/-$/z/')
          echo ::set-output name=result::$deployName

      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.clusterName }}
          resource-group: ${{ env.resourceGroup }}

      - name: Remove PR Deployment
        run: kubectl delete deploy ${{steps.generate-deployment-name.outputs.result}} --namespace ${{ env.nameSpace }}
