name: Pull Request Closed

on:
  pull_request:
    types: [closed]

env:
  # azure
  resourceGroup: jldeen2022k8s
  clusterName: jldeen2022k8s

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create valid child namespace name
        id: generate-child-space-name
        run: |
          namespace=${GITHUB_HEAD_REF::63}        
          namespace=$(echo ${namespace//[!0-9a-zA-Z]/-} | tr '[:upper:]' '[:lower:]' | sed -e 's/^-/z/' -e 's/-$/z/')
          echo ::set-output name=result::$namespace

      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.clusterName }}
          resource-group: ${{ env.resourceGroup }}

      - name: Remove PR Namespace
        run: kubectl delete ns ${{steps.generate-child-space-name.outputs.result}}
